openapi: 3.0.3
info:
  title: onecx-ai-management-bff
  version: '1.0'
  description: Updated on 05.06.2025 at 08:41
paths:
  /aIProvider:
    post:
      operationId: createAIProvider
      tags:
        - AIProviderBffService
      description: This operation performs a create.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAIProvider'
      responses:
        '201':
          description: New AIProvider created
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIProviderCreateResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /aIProvider/search:
    post:
      operationId: searchAIProvider
      tags:
        - AIProviderBffService
      description: This operation performs a search based on provided search criteria. Search for AIProvider results.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIProviderSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIProviderSearchResponse'
        '400':
          description: Bad request
        '500':
          description: Something went wrong
  /aIProvider/{id}:
    get:
      x-onecx:
        permissions:
          AIProvider:
            - read
      operationId: getAIProviderById
      tags:
        - AIProviderBffService
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAIProviderByIdResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
    put:
      operationId: updateAIProvider
      tags:
        - AIProviderBffService
      description: This operation performs an update.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAIProvider'
      responses:
        '204':
          description: AIProvider updated
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIProviderUpdateResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: AIProvider not found
    delete:
      tags:
        - AIProviderBffService
      operationId: deleteAIProvider
      description: Delete AIProvider by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: AIProvider deleted
  /aiContext/{id}:
    get:
      x-onecx:
        permissions:
          aiContext:
            - read
      operationId: getAIContextById
      tags:
        - AIContextBffService
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAIContextByIdResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
    put:
      operationId: updateAIContext
      tags:
        - AIContextBffService
      description: This operation performs an update.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAIContextRequest'
      responses:
        '204':
          description: AIContext updated
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAIContextResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: AIContext not found
    delete:
      tags:
        - AIContextBffService
      operationId: deleteAIContext
      description: Delete AIContext by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: AIContext deleted
  /aiContext/search:
    post:
      operationId: searchAIContexts
      tags:
        - AIContextBffService
      description: This operation performs a search based on provided search criteria. Search for aiContext results.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchAIContextRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchAIContextResponse'
        '400':
          description: Bad request
        '500':
          description: Something went wrong
  /aiContext:
    post:
      operationId: createAIContext
      tags:
        - AIContextBffService
      description: This operation performs a create.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAIContextRequest'
      responses:
        '201':
          description: New AIContext created
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAIContextResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /mcpserver/search:
    post:
      operationId: searchMCPServers
      tags:
        - MCPServerBffService
      description: This operation performs a search based on provided search criteria. Search for mcpserver results.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchMCPServerRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchMCPServerResponse'
        '400':
          description: Bad request
  /mcpserver/{id}:
    get:
      x-onecx:
        permissions:
          mcpserver:
            - read
      operationId: getMCPServerById
      tags:
        - MCPServerBffService
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMCPServerByIdResponse'
        '404':
          description: Not Found
    put:
      operationId: updateMCPServer
      tags:
        - MCPServerBffService
      description: This operation performs an update.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMCPServerRequest'
      responses:
        '200':
          description: MCPServer updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMCPServerResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: MCPServer not found
    delete:
      tags:
        - MCPServerBffService
      operationId: deleteMCPServer
      description: Delete MCPServer by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: MCPServer deleted
components:
  schemas:
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    AIProvider:
      type: object
      required:
        - id
      properties:
        modificationCount:
          type: integer
          format: int32
        id:
          type: string
        name:
          type: string
        description:
          type: string
        llmUrl:
          type: string
        appId:
          type: string
        modelName:
          type: string
        modelVersion:
          type: string
        apiKey:
          type: string
    AIProviderSearchRequest:
      type: object
      properties:
        limit:
          type: integer
          maximum: 2500
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        llmUrl:
          type: string
        appId:
          type: string
        modelName:
          type: string
        modelVersion:
          type: string
    AIProviderSearchResponse:
      type: object
      required:
        - results
        - totalNumberOfResults
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/AIProvider'
        totalNumberOfResults:
          type: integer
          format: int32
          description: Total number of results on the server.
    GetAIProviderByIdResponse:
      type: object
      required:
        - result
      properties:
        result:
          $ref: '#/components/schemas/AIProvider'
    CreateAIProvider:
      type: object
      properties:
        dataObject:
          type: object
          $ref: '#/components/schemas/AIProvider'
    UpdateAIProvider:
      type: object
      properties:
        dataObject:
          type: object
          $ref: '#/components/schemas/AIProvider'
    AIProviderCreateResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        llmUrl:
          type: string
        appId:
          type: string
        modelName:
          type: string
        modelVersion:
          type: string
        apiKey:
          type: string
    AIProviderUpdateResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        llmUrl:
          type: string
        appId:
          type: string
        modelName:
          type: string
        modelVersion:
          type: string
        apiKey:
          type: string
    UpdateAIContextRequest:
      type: object
      properties:
        dataObject:
          type: object
          $ref: '#/components/schemas/AIContext'
    UpdateAIContextResponse:
      type: object
      properties:
        dataObject:
          type: object
          $ref: '#/components/schemas/AIContext'
    GetAIContextByIdResponse:
      type: object
      required:
        - result
      properties:
        result:
          $ref: '#/components/schemas/AIContext'
    SearchAIContextRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
          default: 0
          description: The number of the page
        pageSize:
          type: integer
          format: int32
          default: 100
          maximum: 1000
          description: The size of the page.
        name:
          type: string
        description:
          type: string
        appId:
          type: string
    SearchAIContextResponse:
      type: object
      required:
        - stream
        - size
        - number
        - totalPages
        - totalElements
      properties:
        stream:
          type: array
          items:
            $ref: '#/components/schemas/AIContext'
        size:
          type: integer
          format: int32
          description: Current page size.
        number:
          type: integer
          format: int32
          description: Current page number.
        totalElements:
          type: integer
          format: int64
          description: Total number of results on the server.
        totalPages:
          type: integer
          format: int64
          description: Total pages.
    AIContext:
      type: object
      properties:
        id:
          type: string
        appId:
          type: string
        name:
          type: string
        description:
          type: string
        modificationCount:
          type: integer
          format: int32
        modificationUser:
          type: string
        creationUser:
          type: string
        provider:
          $ref: '#/components/schemas/AIProvider'
        mcpServers:
          type: array
          items:
            $ref: '#/components/schemas/MCPServer'
    CreateAIContextRequest:
      type: object
      properties:
        dataObject:
          $ref: '#/components/schemas/AIContext'
    CreateAIContextResponse:
      type: object
      properties:
        dataObject:
          type: object
          $ref: '#/components/schemas/AIContext'
    MCPServer:
      type: object
      required:
        - id
      properties:
        modificationCount:
          type: integer
          format: int32
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        apiKey:
          type: string
        protocol:
          type: string
        aiContext:
          $ref: '#/components/schemas/AIContext'
    SearchMCPServerRequest:
      type: object
      properties:
        id:
          type: string
        pageNumber:
          type: integer
          format: int32
          default: 0
          description: The number of the page
        pageSize:
          type: integer
          format: int32
          default: 100
          maximum: 1000
          description: The size of the page.
        name:
          type: string
        description:
          type: string
        url:
          type: string
        protocol:
          type: string
    SearchMCPServerResponse:
      type: object
      required:
        - stream
        - size
        - number
        - totalPages
        - totalElements
      properties:
        stream:
          type: array
          items:
            $ref: '#/components/schemas/MCPServer'
        size:
          type: integer
          format: int32
          description: Current page size.
        number:
          type: integer
          format: int32
          description: Current page number.
        totalElements:
          type: integer
          format: int64
          description: Total number of results on the server.
        totalPages:
          type: integer
          format: int64
          description: Total pages.
    UpdateMCPServerRequest:
      type: object
      properties:
        resource:
          type: object
          $ref: '#/components/schemas/MCPServer'
    UpdateMCPServerResponse:
      type: object
      properties:
        resource:
          type: object
          $ref: '#/components/schemas/MCPServer'
        # "ACTION DE1: modify data object or use flat list here. https://onecx.github.io/docs/nx-plugins/current/general/getting_started/create-update/extend-form-fields.html#action-1"    
    GetMCPServerByIdResponse:
      type: object
      required:
        - resource
      properties:
        resource:
          $ref: '#/components/schemas/MCPServer'
tags:
  - name: MCPServerBffService
    description: MCPServerBffService related endpoints
