openapi: 3.0.3
info:
  title: onecx-ai-ui-bff
  version: '1.0'
paths:
  /AIKnowledgeBase/search:
    post:
      operationId: searchAIKnowledgeBases
      tags:
        - AIKnowledgeBaseBffService
      description: This operation performs a search based on provided search criteria.
        Search for aIKnowledgeBase results.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIKnowledgeBaseSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIKnowledgeBaseSearchResponse'
        '400':
          description: Bad request
        '500':
          description: Something went wrong
components:
  schemas:
    AIKnowledgeBase:
      type: object
      required:
        - id
        - name
        - description
      properties:
        modificationCount:
          type: integer
          format: int32
        id:
          type: string
        name:
          type: string
        description: 
          type: string
    AIKnowledgeBaseSearchRequest:
      type: object
      properties:
        limit:
          type: integer
          maximum: 2500
        id:
          type: string
        name:
          type: string
        description: 
          type: string
    AIKnowledgeBaseSearchResponse:
      type: object
      required:
        - results
        - totalNumberOfResults
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/AIKnowledgeBase'
        totalNumberOfResults:
          type: integer
          format: int32
          description: Total number of results on the server.
