app:
  name: ui
  image:
    repository: onecx-apps/onecx-ai-management-ui
  routing:
    enabled: true
    path: /mfe/onecxAiUiManagement/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OnecxAiUiManagementModule
          description: OneCX OnecxAiUi Management Module
          note: OneCX OnecxAiUi Management UI module auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-ai-management-ui
          tagName: onecx-ai-management-ui-webcomponent
    permission:
      enabled: true
      spec:
        permissions:
          AI_PROVIDER:
            CREATE: Create AIProvider
            EDIT: Edit AIProvider
            DELETE: Delete AIProvider
            SAVE: Update and save AIProvider
            IMPORT: Import AIProvider
            EXPORT: Export AIProvider
            VIEW: View mode for AIProvider
            SEARCH: Search AIProvider
            CHANGE_API_KEY: Change ApiKey AIProvider
          AI_CONTEXT:
            CREATE: Create aiContext
            EDIT: Edit aiContext
            DELETE: Delete aiContext
            SAVE: Update and save aiContext
            IMPORT: Import aiContext
            EXPORT: Export aiContext
            VIEW: View mode for aiContext
            SEARCH: Search aiContext
            BACK: Back to aiContext
          MCPSERVER:
            CREATE: Create mcpserver
            EDIT: Edit mcpserver
            DELETE: Delete mcpserver
            SAVE: Update and save mcpserver
            IMPORT: Import mcpserver
            EXPORT: Export mcpserver
            VIEW: View mode for mcpserver
            SEARCH: Search mcpserver
            BACK: Navigate back in details of mcpserver
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-ai-management-ui
