app:
  name: ui
  image:
    repository: onecx/onecx-ai-ui
  routing:
    enabled: true
    path: /mfe/onecxAiUi/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OnecxAiUiModule
          description: OneCX OnecxAiUi Module
          note: OneCX OnecxAiUi UI module auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-ai-ui
          tagName: onecx-ai-ui-webcomponent
    permission:
      enabled: true
      spec:
        permissions:
          AI_KNOWLEDGE_BASE:
            CREATE: Create AIKnowledgeBase
            EDIT: Edit AIKnowledgeBase
            DELETE: Delete AIKnowledgeBase
            SAVE: Update and save AIKnowledgeBase
            IMPORT: Import AIKnowledgeBase
            EXPORT: Export AIKnowledgeBase
            VIEW: View mode for AIKnowledgeBase
            SEARCH: Search AIKnowledgeBase
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-ai-ui
